window.HETEROSIS_PAPERS = [
  {
    id: "shull-1908",
    title: "The Composition of a Field of Maize",
    titleZh: "玉米田间的组成：杂种优势研究的奠基表述",
    authors: "Shull, G. H.",
    journal: "American Breeders Association Reports",
    year: 1908,
    volume: "4",
    pages: "296–301",
    doi: "",
    category: "经典奠基",
    themes: ["经典假说", "育种应用"],
    crops: ["玉米"],
    type: "经典论文",
    importance: "奠基",
    summary:
      "Shull 系统讨论玉米自交衰退与杂交恢复，首次将“heterosis”概念化的核心现象带入育种视野。该文奠定了利用自交系配制杂交种、通过杂种优势提高产量的技术路线。",
    finding:
      "自交导致群体活力下降，而不同自交系杂交后，后代在株高、产量与适应度上普遍恢复甚至超过亲本。",
    keywords: ["heterosis", "maize", "inbreeding depression", "selfing", "hybrid seed"]
  },
  {
    id: "east-1908",
    title: "Inbreeding in Corn",
    titleZh: "玉米的自交：自交衰退与杂交恢复的早期证据",
    authors: "East, E. M.",
    journal: "Connecticut Agricultural Experiment Station Report",
    year: 1908,
    volume: "",
    pages: "419–428",
    doi: "",
    category: "经典奠基",
    themes: ["经典假说", "育种应用"],
    crops: ["玉米"],
    type: "经典论文",
    importance: "奠基",
    summary:
      "East 通过玉米连续自交与杂交试验，建立了对近交衰退和杂种恢复活力的早期系统观察。其结论与 Shull 的工作共同推动现代杂交玉米产业兴起。",
    finding:
      "连续自交使多个农艺性状显著退化，而杂交可恢复活力；不同自交系之间的遗传差异是产生杂种优势的重要条件。",
    keywords: ["maize", "inbreeding", "crossbreeding", "hybrid vigor", "yield"]
  },
  {
    id: "bruce-1910",
    title: "The Mendelian Theory of Heredity and the Augmentation of Vigor",
    titleZh: "孟德尔遗传理论与活力增强",
    authors: "Bruce, A. B.",
    journal: "Science",
    year: 1910,
    volume: "32",
    pages: "627–628",
    doi: "",
    category: "经典奠基",
    themes: ["经典假说"],
    crops: ["综合"],
    type: "经典论文",
    importance: "奠基",
    summary:
      "Bruce 从孟德尔遗传角度解释杂种活力，将有利显性基因的互补聚集视为后代超过亲本的重要原因。该思路后来发展成解释杂种优势的显性假说。",
    finding:
      "不同亲本携带的有利显性等位基因在杂交后代中互补，可遮蔽不利隐性等位基因并提升综合表现。",
    keywords: ["dominance hypothesis", "Mendelian genetics", "hybrid vigor", "vigor"]
  },
  {
    id: "jones-1918",
    title: "The Effects of Inbreeding and Crossbreeding upon Development",
    titleZh: "自交与杂交对发育的影响",
    authors: "Jones, D. F.",
    journal: "Connecticut Agricultural Experiment Station Bulletin",
    year: 1918,
    volume: "207",
    pages: "5–100",
    doi: "",
    category: "经典奠基",
    themes: ["经典假说", "育种应用"],
    crops: ["玉米"],
    type: "经典论文",
    importance: "奠基",
    summary:
      "Jones 将双杂交制种方案系统化，解决了单交种种子成本高的问题，是杂种优势理论转化为规模化农业生产的里程碑。",
    finding:
      "双交种方案能够在保持较高杂种优势的同时提高制种效率，为杂交玉米的大面积推广提供可行路径。",
    keywords: ["double cross", "maize breeding", "seed production", "hybrid corn"]
  },
  {
    id: "hull-1945",
    title: "Recurrent Selection for Specific Combining Ability in Corn",
    titleZh: "玉米特殊配合力的轮回选择",
    authors: "Hull, F. H.",
    journal: "Journal of the American Society of Agronomy",
    year: 1945,
    volume: "37",
    pages: "134–145",
    doi: "",
    category: "经典奠基",
    themes: ["遗传解析", "育种应用"],
    crops: ["玉米"],
    type: "育种应用",
    importance: "里程碑",
    summary:
      "Hull 将一般配合力与特殊配合力概念用于轮回选择，强调非加性遗传效应对杂交组合表现的重要性。该框架深刻影响了现代杂交育种设计。",
    finding:
      "针对特殊配合力的轮回选择可持续改变群体组合能力，表明基因互作在杂种优势形成中占据关键位置。",
    keywords: ["combining ability", "recurrent selection", "epistasis", "maize"]
  },
  {
    id: "crow-1948",
    title: "Alternative Hypotheses of Hybrid Vigor",
    titleZh: "杂种活力的替代假说",
    authors: "Crow, J. F.",
    journal: "Genetics",
    year: 1948,
    volume: "33",
    pages: "477–487",
    doi: "10.1093/genetics/33.5.477",
    category: "经典奠基",
    themes: ["经典假说", "遗传解析"],
    crops: ["综合"],
    type: "经典论文",
    importance: "奠基",
    summary:
      "Crow 对显性假说、超显性假说等竞争性解释进行清晰梳理，使杂种优势从育种观察转向可检验的群体遗传学问题。",
    finding:
      "显性与超显性都能产生杂种活力，但两类模型对基因型—表型关系作出不同预测，需要遗传实验加以区分。",
    keywords: ["dominance", "overdominance", "hybrid vigor", "population genetics"]
  },
  {
    id: "stuber-1992",
    title:
      "Identification of Genetic Factors Contributing to Heterosis in a Hybrid from Two Elite Maize Inbred Lines Using Molecular Markers",
    titleZh: "利用分子标记鉴定两个优良玉米自交系杂种优势的遗传因子",
    authors: "Stuber, C. W.; Lincoln, S. E.; Wolff, D. W.; Helentjaris, T.; Lander, E. S.",
    journal: "Genetics",
    year: 1992,
    volume: "132",
    pages: "823–839",
    doi: "10.1093/genetics/132.3.823",
    category: "遗传解析",
    themes: ["QTL与基因互作", "遗传解析"],
    crops: ["玉米"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "该研究率先以分子标记系统定位影响玉米杂种优势的 QTL，将经典假说转化为可追踪的染色体区间与效应估计。",
    finding:
      "多个 QTL 对杂种优势具有显著贡献，显性效应占主导，但部分位点同时呈现超显性和上位性特征。",
    keywords: ["QTL", "molecular markers", "dominance", "overdominance", "maize heterosis"]
  },
  {
    id: "xiao-1995",
    title:
      "Dominance Is the Major Genetic Basis of Heterosis in Rice as Revealed by QTL Analysis Using Molecular Markers",
    titleZh: "分子标记 QTL 分析揭示显性是水稻杂种优势的主要遗传基础",
    authors: "Xiao, J.; Li, J.; Yuan, L.; Tanksley, S. D.",
    journal: "Genetics",
    year: 1995,
    volume: "140",
    pages: "745–754",
    doi: "10.1093/genetics/140.2.745",
    category: "遗传解析",
    themes: ["QTL与基因互作", "遗传解析"],
    crops: ["水稻"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "研究以水稻籼粳杂交组合定位杂种优势相关 QTL，是作物杂种优势分子解析的早期代表性工作。",
    finding:
      "大多数优势 QTL 的效应方向与显性模型一致，支持显性互补是水稻杂种优势的主要来源之一。",
    keywords: ["rice", "QTL", "dominance", "heterosis", "molecular markers"]
  },
  {
    id: "yu-1997",
    title: "Importance of Epistasis as the Genetic Basis of Heterosis in an Elite Rice Hybrid",
    titleZh: "上位性是优良水稻杂交种杂种优势的重要遗传基础",
    authors: "Yu, S. B.; Li, J. X.; Xu, C. G.; Tan, Y. F.; Gao, Y. J.; Li, X. H.; Zhang, Q.; Saghai Maroof, M. A.",
    journal: "Proceedings of the National Academy of Sciences",
    year: 1997,
    volume: "94",
    pages: "9226–9231",
    doi: "10.1073/pnas.94.17.9226",
    category: "遗传解析",
    themes: ["QTL与基因互作", "遗传解析"],
    crops: ["水稻"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "该研究以水稻重组自交系与测交组合分析杂种优势的遗传结构，强调上位性互作在优良杂交种中的关键作用。",
    finding:
      "多位点互作能够解释相当一部分杂种优势，单独依赖单位点显性效应不足以完整描述复杂产量性状。",
    keywords: ["epistasis", "rice", "heterosis", "quantitative genetics"]
  },
  {
    id: "hua-2003",
    title:
      "Single-Locus Heterotic Effects and Dominance by Dominance Interactions Can Adequately Explain the Genetic Basis of Heterosis in an Elite Rice Hybrid",
    titleZh: "单位点优势效应与显性×显性互作可充分解释优良水稻杂交种的杂种优势",
    authors: "Hua, J.; Xing, Y.; Wu, W.; Xu, C.; Sun, X.; Yu, S.; Zhang, Q.",
    journal: "Proceedings of the National Academy of Sciences",
    year: 2003,
    volume: "100",
    pages: "2574–2579",
    doi: "10.1073/pnas.0437907100",
    category: "遗传解析",
    themes: ["QTL与基因互作", "遗传解析"],
    crops: ["水稻"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "研究使用永久性遗传群体精细分析水稻杂种优势的位点效应，提出显性与显性×显性互作的组合解释。",
    finding:
      "单位点显性效应和上位性共同构成水稻杂种优势，未发现必须依赖普遍超显性才能解释的模式。",
    keywords: ["dominance", "epistasis", "rice", "yield heterosis", "QTL"]
  },
  {
    id: "birchler-2003",
    title: "In Search of the Molecular Basis of Heterosis",
    titleZh: "寻找杂种优势的分子基础",
    authors: "Birchler, J. A.; Auger, D. L.; Riddle, N. C.",
    journal: "The Plant Cell",
    year: 2003,
    volume: "15",
    pages: "2236–2239",
    doi: "10.1105/tpc.151030",
    category: "分子机制",
    themes: ["转录与代谢", "表观遗传"],
    crops: ["综合"],
    type: "综述",
    importance: "核心",
    summary:
      "作者把杂种优势的遗传解释推进到基因表达与调控层面，讨论等位基因表达差异、非加性转录和剂量效应。",
    finding:
      "杂种优势可能来自多层次的表达调控，而非单一“超显性基因”；转录组与表观调控应纳入统一解释框架。",
    keywords: ["gene expression", "nonadditive expression", "dosage", "heterosis"]
  },
  {
    id: "semel-2006",
    title: "Overdominant Quantitative Trait Loci for Yield and Fitness in Tomato",
    titleZh: "番茄产量与适合度性状的超显性数量性状位点",
    authors: "Semel, Y.; Nissenbaum, J.; Menda, N.; Zinder, M.; Krieger, U.; Issman, N.; Pleban, T.; Lippman, Z.; Gur, A.; Zamir, D.",
    journal: "Proceedings of the National Academy of Sciences",
    year: 2006,
    volume: "103",
    pages: "12981–12986",
    doi: "10.1073/pnas.0604585103",
    category: "遗传解析",
    themes: ["QTL与基因互作", "遗传解析"],
    crops: ["番茄"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "研究利用番茄导入系定位产量和适合度相关 QTL，为超显性在特定复杂性状中的作用提供了经典证据。",
    finding:
      "若干产量与适合度 QTL 在杂合状态表现最佳，显示超显性效应可在特定位点上显著贡献杂种优势。",
    keywords: ["overdominance", "tomato", "QTL", "yield", "fitness"]
  },
  {
    id: "lippman-2007",
    title: "Heterosis: Revisiting the Magic",
    titleZh: "重新审视杂种优势这一“遗传魔力”",
    authors: "Lippman, Z. B.; Zamir, D.",
    journal: "Trends in Genetics",
    year: 2007,
    volume: "23",
    pages: "60–66",
    doi: "10.1016/j.tig.2006.12.006",
    category: "分子机制",
    themes: ["经典假说", "QTL与基因互作"],
    crops: ["综合"],
    type: "综述",
    importance: "核心",
    summary:
      "两位番茄遗传学家回顾杂种优势的竞争性假说，主张从单基因二元模型转向多位点效应和复杂调控网络。",
    finding:
      "显性、超显性与上位性并非互斥，同一作物或性状的不同位点可能由不同机制共同塑造杂种优势。",
    keywords: ["heterosis", "overdominance", "epistasis", "QTL", "review"]
  },
  {
    id: "hochholdinger-2007",
    title: "Towards the Molecular Basis of Heterosis",
    titleZh: "走向杂种优势的分子基础",
    authors: "Hochholdinger, F.; Hoecker, N.",
    journal: "Trends in Plant Science",
    year: 2007,
    volume: "12",
    pages: "427–432",
    doi: "10.1016/j.tplants.2007.08.007",
    category: "分子机制",
    themes: ["转录与代谢", "表观遗传"],
    crops: ["玉米", "拟南芥"],
    type: "综述",
    importance: "核心",
    summary:
      "作者整合遗传学、转录组和蛋白组证据，强调杂种优势并不是静态终点，而是发育过程中动态形成的调控结果。",
    finding:
      "不同发育阶段与组织中的非加性表达、蛋白互作和代谢补偿，可能共同构成杂种表型的分子基础。",
    keywords: ["transcriptome", "proteome", "development", "maize", "Arabidopsis"]
  },
  {
    id: "charlesworth-2009",
    title: "The Genetics of Inbreeding Depression",
    titleZh: "近交衰退的遗传学",
    authors: "Charlesworth, D.; Willis, J. H.",
    journal: "Nature Reviews Genetics",
    year: 2009,
    volume: "10",
    pages: "783–796",
    doi: "10.1038/nrg2664",
    category: "遗传解析",
    themes: ["经典假说", "遗传解析"],
    crops: ["综合"],
    type: "综述",
    importance: "核心",
    summary:
      "文章系统梳理近交衰退的显性有害突变、超显性与频率依赖选择等解释，是理解杂交恢复活力所必需的对照背景。",
    finding:
      "近交衰退通常由有害隐性等位基因纯合、超显性位点纯合及环境互作共同造成，不同群体的贡献比例存在差异。",
    keywords: ["inbreeding depression", "deleterious alleles", "overdominance", "mutation load"]
  },
  {
    id: "he-2010",
    title:
      "Global Epigenetic and Transcriptional Trends among Two Rice Subspecies and Their Reciprocal Hybrids",
    titleZh: "两个水稻亚种及正反交杂种的全球表观与转录趋势",
    authors: "He, G.; Zhu, X.; Elling, A. A.; Chen, L.; Wang, X.; Guo, L.; Liang, M.; He, H.; Zhang, H.; Chen, F.; Qi, Y.; Chen, R.; Deng, X. W.",
    journal: "The Plant Cell",
    year: 2010,
    volume: "22",
    pages: "17–33",
    doi: "10.1105/tpc.109.072208",
    category: "表观遗传",
    themes: ["表观遗传", "转录与代谢"],
    crops: ["水稻"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究比较水稻亚种和正反交杂种中的 DNA 甲基化、小 RNA 与基因表达变化，展示表观层面的非加性状态。",
    finding:
      "杂交可改变部分基因组区域的甲基化和小 RNA 丰度，并与基因表达的非加性变化相关联。",
    keywords: ["DNA methylation", "small RNA", "rice hybrid", "epigenetics", "reciprocal cross"]
  },
  {
    id: "chen-2010",
    title: "Molecular Mechanisms of Polyploidy and Hybrid Vigor",
    titleZh: "多倍化与杂种活力的分子机制",
    authors: "Chen, Z. J.",
    journal: "Trends in Plant Science",
    year: 2010,
    volume: "15",
    pages: "57–71",
    doi: "10.1016/j.tplants.2009.12.003",
    category: "分子机制",
    themes: ["表观遗传", "转录与代谢"],
    crops: ["综合"],
    type: "综述",
    importance: "核心",
    summary:
      "文章把多倍体优势与种间杂种优势放在统一框架中，讨论剂量效应、表观重塑和调控网络重组。",
    finding:
      "杂交与多倍化都可能触发基因表达重编程和表观变化，产生亲本中不存在的调控状态。",
    keywords: ["polyploidy", "hybrid vigor", "dosage", "epigenetic reprogramming"]
  },
  {
    id: "groszmann-2011",
    title:
      "Changes in 24-nt siRNA Levels in Arabidopsis Hybrids Suggest an Epigenetic Contribution to Hybrid Vigor",
    titleZh: "拟南芥杂交种中 24-nt siRNA 水平变化提示表观遗传贡献",
    authors: "Groszmann, M.; Greaves, I. K.; Albertyn, Z. I.; Scofield, G. N.; Peacock, W. J.; Dennis, E. S.",
    journal: "Proceedings of the National Academy of Sciences",
    year: 2011,
    volume: "108",
    pages: "2617–2622",
    doi: "10.1073/pnas.1014378108",
    category: "表观遗传",
    themes: ["表观遗传"],
    crops: ["拟南芥"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "研究显示拟南芥杂交种中 24-nt siRNA 的丰度与分布发生非加性变化，为表观遗传参与杂种优势提供直接线索。",
    finding:
      "部分 siRNA 位点在杂交种中相对亲本下调，并伴随邻近基因表达变化，支持小 RNA 介导的表观调控模型。",
    keywords: ["24-nt siRNA", "Arabidopsis", "hybrid vigor", "epigenetics", "nonadditive"]
  },
  {
    id: "riedelsheimer-2012",
    title: "Genomic and Metabolic Prediction of Complex Heterotic Traits in Hybrid Maize",
    titleZh: "杂交玉米复杂杂种优势性状的基因组与代谢组预测",
    authors: "Riedelsheimer, C.; Czedik-Eysenberg, A.; Grieder, C.; Lisec, J.; Technow, F.; Sulpice, R.; Altmann, T.; Stitt, M.; Willmitzer, L.; Melchinger, A. E.",
    journal: "Nature Genetics",
    year: 2012,
    volume: "44",
    pages: "217–220",
    doi: "10.1038/ng.1033",
    category: "基因组与预测",
    themes: ["基因组与预测", "转录与代谢", "育种应用"],
    crops: ["玉米"],
    type: "育种应用",
    importance: "里程碑",
    summary:
      "研究将基因组与代谢组信息用于预测玉米杂交种表现，证明组学数据可提升复杂杂种优势性状的预测效率。",
    finding:
      "整合 SNP 与代谢物标记能够较准确预测多个杂种性能指标，为数据驱动的杂种组合筛选提供早期范例。",
    keywords: ["genomic prediction", "metabolomics", "hybrid maize", "heterotic traits"]
  },
  {
    id: "shen-2012",
    title:
      "Genome-Wide Analysis of DNA Methylation and Gene Expression Changes in Two Arabidopsis Ecotypes and Their Reciprocal Hybrids",
    titleZh: "两种拟南芥生态型及其正反交杂种的 DNA 甲基化与表达全基因组分析",
    authors: "Shen, H.; He, H.; Li, J.; Chen, W.; Wang, X.; Guo, L.; Peng, Z.; He, G.; Zhong, S.; Qi, Y.; Terzaghi, W.; Deng, X. W.",
    journal: "The Plant Cell",
    year: 2012,
    volume: "24",
    pages: "875–892",
    doi: "10.1105/tpc.111.094870",
    category: "表观遗传",
    themes: ["表观遗传", "转录与代谢"],
    crops: ["拟南芥"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究构建拟南芥正反交杂种的甲基化与转录图谱，比较亲本与杂种之间的非加性变化及其对应关系。",
    finding:
      "杂交可诱导差异甲基化区域并改变邻近基因表达，正反交差异说明亲本来源会影响表观重编程。",
    keywords: ["DNA methylation", "gene expression", "reciprocal hybrids", "Arabidopsis"]
  },
  {
    id: "schnable-2013",
    title: "Progress Toward Understanding Heterosis in Crop Plants",
    titleZh: "作物杂种优势理解进展",
    authors: "Schnable, P. S.; Springer, N. M.",
    journal: "Annual Review of Plant Biology",
    year: 2013,
    volume: "64",
    pages: "71–88",
    doi: "10.1146/annurev-arplant-042110-103827",
    category: "分子机制",
    themes: ["经典假说", "QTL与基因互作", "转录与代谢"],
    crops: ["玉米", "水稻", "综合"],
    type: "综述",
    importance: "核心",
    summary:
      "这是一篇面向作物研究的综合性综述，回顾遗传模型、组学证据以及杂种优势预测与利用中的主要难点。",
    finding:
      "复杂性状的杂种优势由多位点、多层级调控共同决定，尚未有单一分子机制能够普遍解释全部作物表现。",
    keywords: ["crop heterosis", "genetics", "transcriptomics", "prediction", "maize", "rice"]
  },
  {
    id: "chen-2013",
    title: "Genomic and Epigenetic Insights into the Molecular Bases of Heterosis",
    titleZh: "杂种优势分子基础的基因组与表观遗传启示",
    authors: "Chen, Z. J.",
    journal: "Nature Reviews Genetics",
    year: 2013,
    volume: "14",
    pages: "471–482",
    doi: "10.1038/nrg3508",
    category: "表观遗传",
    themes: ["表观遗传", "转录与代谢", "经典假说"],
    crops: ["综合"],
    type: "综述",
    importance: "核心",
    summary:
      "Chen 提出从基因组结构与表观调控角度整合杂种优势解释，强调等位基因互作、表达剂量和染色体环境。",
    finding:
      "杂种优势可被视作亲本基因组合并后产生的调控网络重组，显性、超显性和表观效应在系统中相互交织。",
    keywords: ["epigenetics", "genomic architecture", "heterosis", "regulatory network"]
  },
  {
    id: "xu-2014",
    title: "Genomic Selection of Hybrid Performance in Rice (Oryza sativa L.)",
    titleZh: "水稻杂交种表现的基因组选择",
    authors: "Xu, S.; Zhu, D.; Zhang, Q.",
    journal: "The Plant Genome",
    year: 2014,
    volume: "7",
    pages: "1–11",
    doi: "10.3835/plantgenome2013.10.0034",
    category: "基因组与预测",
    themes: ["基因组与预测", "育种应用"],
    crops: ["水稻"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究评估基因组选择预测水稻杂交种表现的能力，为高密度标记辅助杂交组合筛选提供方法基础。",
    finding:
      "结合亲本标记信息与训练群体表型，可在未测配组合中预测部分杂种性能，但预测精度受群体结构和性状遗传力影响。",
    keywords: ["genomic selection", "hybrid rice", "prediction accuracy", "marker"]
  },
  {
    id: "huang-2015",
    title:
      "Genomic Analysis of Hybrid Rice Varieties Reveals Numerous Superior Alleles That Contribute to Heterosis",
    titleZh: "杂交稻基因组分析揭示大量有助于杂种优势的优良等位基因",
    authors: "Huang, X.; Yang, S.; Gong, J.; Zhao, Y.; Feng, Q.; Gong, H.; Li, W.; Zhan, Q.; Cheng, B.; Xia, J.; et al.",
    journal: "Nature Communications",
    year: 2015,
    volume: "6",
    pages: "6258",
    doi: "10.1038/ncomms7258",
    category: "基因组与预测",
    themes: ["基因组与预测", "育种应用", "遗传解析"],
    crops: ["水稻"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "研究通过大规模杂交稻品种重测序，识别可能由亲本组合获得的优良等位基因，连接基因组变异与杂种表现。",
    finding:
      "杂交稻基因组中富集多个与产量和适应相关的高频优良等位基因，部分组合可能通过互补改良综合性状。",
    keywords: ["hybrid rice", "resequencing", "superior alleles", "heterosis", "genomics"]
  },
  {
    id: "huang-2016",
    title: "Genomic Architecture of Heterosis for Yield Traits in Rice",
    titleZh: "水稻产量性状杂种优势的基因组结构",
    authors: "Huang, X.; Yang, S.; Gong, J.; Zhao, Q.; Feng, Q.; Zhan, Q.; Zhao, Y.; Li, W.; Cheng, B.; Xia, J.; et al.",
    journal: "Nature",
    year: 2016,
    volume: "537",
    pages: "629–633",
    doi: "10.1038/nature19760",
    category: "基因组与预测",
    themes: ["QTL与基因互作", "基因组与预测", "遗传解析"],
    crops: ["水稻"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "研究以大规模杂交组合和基因组数据解析产量杂种优势，发现大量分散的小效应位点而非少数超大效应位点。",
    finding:
      "水稻产量杂种优势呈高度多基因结构，显性互补效应广泛存在，并叠加部分上位性互作。",
    keywords: ["heterosis architecture", "rice yield", "polygenic", "dominance", "epistasis"]
  },
  {
    id: "yang-2017",
    title: "Genomic Architecture of Biomass Heterosis in Arabidopsis",
    titleZh: "拟南芥生物量杂种优势的基因组结构",
    authors: "Yang, M.; Wang, X.; Ren, D.; Huang, H.; Xu, M.; He, G.; Deng, X. W.",
    journal: "Proceedings of the National Academy of Sciences",
    year: 2017,
    volume: "114",
    pages: "8101–8106",
    doi: "10.1073/pnas.1705423114",
    category: "基因组与预测",
    themes: ["QTL与基因互作", "转录与代谢", "表观遗传"],
    crops: ["拟南芥"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究结合多亲本群体、转录组和杂种表现剖析拟南芥生物量优势，强调多位点互作与表达变异。",
    finding:
      "生物量杂种优势可由大量微效位点共同贡献，并与亲本等位基因组合和转录网络变化密切相关。",
    keywords: ["biomass heterosis", "Arabidopsis", "genomic architecture", "expression"]
  },
  {
    id: "crossa-2017",
    title: "Genomic Selection in Plant Breeding: Methods, Models, and Perspectives",
    titleZh: "植物育种中的基因组选择：方法、模型与展望",
    authors: "Crossa, J.; Pérez-Rodríguez, P.; Cuevas, J.; Montesinos-López, O.; Jarquín, D.; de los Campos, G.; Burgueño, J.; González-Camacho, J. M.; Pérez-Elizalde, S.; Beyene, Y.; Dreisigacker, S.; Singh, R.; Zhang, X.; Gowda, M.; Roorkiwal, M.; Rutkoski, J.; Varshney, R. K.",
    journal: "Trends in Plant Science",
    year: 2017,
    volume: "22",
    pages: "961–975",
    doi: "10.1016/j.tplants.2017.08.011",
    category: "基因组与预测",
    themes: ["基因组与预测", "育种应用"],
    crops: ["综合"],
    type: "综述",
    importance: "核心",
    summary:
      "文章系统总结植物基因组选择的统计模型、训练策略和应用场景，为预测杂交种表现提供方法学框架。",
    finding:
      "模型预测能力取决于训练群体设计、标记密度、性状遗传结构以及基因型与环境互作，单一模型难以适用所有育种场景。",
    keywords: ["genomic selection", "prediction models", "plant breeding", "GxE"]
  },
  {
    id: "wallace-2018",
    title:
      "On the Road to Breeding 4.0: Unraveling the Good, the Bad, and the Boring of Crop Quantitative Genomics",
    titleZh: "迈向育种 4.0：解析作物数量基因组学中的有利、不利与中性变异",
    authors: "Wallace, J. G.; Rodgers-Melnick, E.; Buckler, E. S.",
    journal: "Annual Review of Genetics",
    year: 2018,
    volume: "52",
    pages: "421–444",
    doi: "10.1146/annurev-genet-120116-024419",
    category: "基因组与预测",
    themes: ["基因组与预测", "育种应用"],
    crops: ["综合"],
    type: "综述",
    importance: "核心",
    summary:
      "文章展望“育种 4.0”时代如何利用数量基因组学、预测模型和育种技术整合复杂性状改良，为杂种优势利用提供宏观方向。",
    finding:
      "未来育种需要把因果变异、背景依赖效应、环境互作与大规模表型数据结合，才能更可靠地设计优良杂交组合。",
    keywords: ["breeding 4.0", "quantitative genomics", "prediction", "crop improvement"]
  },
  {
    id: "kearsey-1968",
    title:
      "A General Method of Detecting Additive, Dominance and Epistatic Variation for Metrical Traits. I. Theory",
    titleZh: "数量性状加性、显性与上位性变异的通用检测方法：理论",
    authors: "Kearsey, M. J.; Jinks, J. L.",
    journal: "Heredity",
    year: 1968,
    volume: "23",
    pages: "403–409",
    doi: "10.1038/hdy.1968.51",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析"],
    crops: ["综合"],
    type: "经典论文",
    importance: "里程碑",
    summary:
      "该文建立利用世代均值与家系设计分解加性、显性和上位性效应的理论框架，是数量性状位点鉴定与杂种优势遗传解析的重要方法学源头。",
    finding:
      "通过系统组合亲本、F1、F2及回交世代，可以估计不同遗传效应的大小，并检验上位性对复杂性状的贡献。",
    keywords: ["biometrical genetics", "generation means", "epistasis", "dominance"]
  },
  {
    id: "cockerham-1996",
    title: "Design III with Marker Loci",
    titleZh: "结合分子标记的设计 III",
    authors: "Cockerham, C. C.; Zeng, Z. B.",
    journal: "Genetics",
    year: 1996,
    volume: "143",
    pages: "1437–1456",
    doi: "10.1093/genetics/143.3.1437",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析"],
    crops: ["综合"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "文章把经典 Design III 与分子标记结合，提出从重组自交系与亲本回交后代中估计位点加性和显性效应的方法。",
    finding:
      "标记辅助 Design III 能够定位并估计多位点显性效应，为检验显性与超显性假说提供严密统计框架。",
    keywords: ["Design III", "marker loci", "additive effect", "dominance effect"]
  },
  {
    id: "li-2001-overdominant-i",
    title:
      "Overdominant Epistatic Loci Are the Primary Genetic Basis of Inbreeding Depression and Heterosis in Rice. I. Biomass and Grain Yield",
    titleZh: "超显性上位位点是水稻近交衰退与杂种优势的主要遗传基础 I：生物量与产量",
    authors: "Li, Z. K.; Luo, L. J.; Mei, H. W.; Wang, D. L.; Shu, Q. Y.; Tabien, R.; Zhong, D. B.; Yang, D. C.; Stansel, J. W.; Khush, G. S.; Paterson, A. H.",
    journal: "Genetics",
    year: 2001,
    volume: "158",
    pages: "1737–1753",
    doi: "10.1093/genetics/158.4.1737",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析"],
    crops: ["水稻"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "研究利用水稻永久性群体系统定位生物量和产量杂种优势相关位点，并把近交衰退与杂种优势放在同一遗传框架中比较。",
    finding:
      "多个超显性上位位点对生物量与产量具有显著贡献，支持高阶基因互作在强优势水稻组合中的重要性。",
    keywords: ["rice", "overdominance", "epistasis", "biomass", "grain yield"]
  },
  {
    id: "luo-2001-overdominant-ii",
    title:
      "Overdominant Epistatic Loci Are the Primary Genetic Basis of Inbreeding Depression and Heterosis in Rice. II. Grain Yield Components",
    titleZh: "超显性上位位点是水稻近交衰退与杂种优势的主要遗传基础 II：产量构成",
    authors: "Luo, L. J.; Li, Z. K.; Mei, H. W.; Shu, Q. Y.; Tabien, R.; Zhong, D. B.; Yang, D. C.; Stansel, J. W.; Khush, G. S.; Paterson, A. H.",
    journal: "Genetics",
    year: 2001,
    volume: "158",
    pages: "1755–1771",
    doi: "10.1093/genetics/158.4.1755",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析"],
    crops: ["水稻"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "文章聚焦水稻穗数、粒数和粒重等产量构成性状，定位与其杂种优势相关的遗传位点及互作效应。",
    finding:
      "产量构成性状的优势效应多由分散位点和上位互作共同决定，不同构成性状的遗传结构存在明显差异。",
    keywords: ["yield components", "rice", "overdominance", "epistasis", "QTL"]
  },
  {
    id: "hua-2002",
    title:
      "Genetic Dissection of an Elite Rice Hybrid Revealed That Heterozygotes Are Not Always Advantageous for Performance",
    titleZh: "优良水稻杂交种的遗传解析表明杂合并非总带来性能优势",
    authors: "Hua, J.; Xing, Y.; Xu, C.; Sun, X.; Yu, S.; Zhang, Q.",
    journal: "Genetics",
    year: 2002,
    volume: "162",
    pages: "1885–1895",
    doi: "10.1093/genetics/162.4.1885",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析"],
    crops: ["水稻"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "研究以永久性 F2 群体和测交设计剖析优良水稻杂交种，检验“杂合即优势”的普遍性。",
    finding:
      "并非所有杂合位点都优于两种纯合基因型，许多位点的优势方向具有性状和背景依赖性。",
    keywords: ["heterozygote advantage", "rice hybrid", "immortalized F2", "QTL"]
  },
  {
    id: "frascaroli-2007",
    title:
      "Classical Genetic and Quantitative Trait Loci Analyses of Heterosis in a Maize Hybrid between Two Elite Inbred Lines",
    titleZh: "两个优良玉米自交系杂交种杂种优势的经典遗传与 QTL 分析",
    authors: "Frascaroli, E.; Cane, M. A.; Landi, P.; Pea, G.; Gianfranceschi, L.; Villa, M.; Morgante, M.; Pè, M. E.",
    journal: "Genetics",
    year: 2007,
    volume: "176",
    pages: "625–644",
    doi: "10.1534/genetics.106.064493",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析"],
    crops: ["玉米"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究结合世代均值分析和 QTL 定位，系统估计一个优良玉米杂交种中产量与株型性状的遗传效应。",
    finding:
      "显性和上位性效应共同解释大部分杂种优势，QTL 效应在不同性状间具有明显异质性。",
    keywords: ["maize hybrid", "QTL", "epistasis", "grain yield", "heterosis"]
  },
  {
    id: "kusterer-2007",
    title:
      "Heterosis for Biomass-Related Traits in Arabidopsis Investigated by Quantitative Trait Loci Analysis of the Triple Testcross Design with Recombinant Inbred Lines",
    titleZh: "利用重组自交系三重测交设计定位拟南芥生物量杂种优势 QTL",
    authors: "Kusterer, B.; Muminovic, J.; Utz, H. F.; Piepho, H. P.; Barth, S.; Heckenberger, M.; Meyer, R. C.; Altmann, T.; Melchinger, A. E.",
    journal: "Genetics",
    year: 2007,
    volume: "177",
    pages: "1839–1850",
    doi: "10.1534/genetics.107.077289",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析"],
    crops: ["拟南芥"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究用三重测交和重组自交系定位拟南芥生物量相关杂种优势位点，并分解加性、显性与上位效应。",
    finding:
      "生物量优势呈多位点结构，显性与上位性共同作用，单一超显性模型难以覆盖全部观测结果。",
    keywords: ["Arabidopsis", "triple testcross", "biomass", "QTL", "epistasis"]
  },
  {
    id: "garcia-2008",
    title: "Quantitative Trait Loci Mapping and the Genetic Basis of Heterosis in Maize and Rice",
    titleZh: "玉米和水稻杂种优势遗传基础的 QTL 定位",
    authors: "Garcia, A. A. F.; Wang, S.; Melchinger, A. E.; Zeng, Z. B.",
    journal: "Genetics",
    year: 2008,
    volume: "180",
    pages: "1707–1724",
    doi: "10.1534/genetics.107.082867",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析"],
    crops: ["玉米", "水稻"],
    type: "机制研究",
    importance: "核心",
    summary:
      "文章比较玉米和水稻杂种优势的 QTL 定位结果，讨论设计、遗传背景和统计模型对机制解释的影响。",
    finding:
      "两种作物的优势位点均可由显性、超显性与上位性组合解释，但不同群体和性状会呈现不同主导模式。",
    keywords: ["maize", "rice", "QTL mapping", "dominance", "overdominance", "epistasis"]
  },
  {
    id: "radoev-2008",
    title:
      "Genetic Analysis of Heterosis for Yield and Yield Components in Rapeseed (Brassica napus L.) by Quantitative Trait Locus Mapping",
    titleZh: "通过 QTL 定位解析甘蓝型油菜产量及产量构成杂种优势",
    authors: "Radoev, M.; Becker, H. C.; Ecke, W.",
    journal: "Genetics",
    year: 2008,
    volume: "179",
    pages: "1547–1558",
    doi: "10.1534/genetics.108.089680",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析", "育种应用"],
    crops: ["油菜"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究在油菜双单倍体群体与测交组合中定位产量杂种优势相关 QTL，把作物杂种优势位点解析拓展到油料作物。",
    finding:
      "多种 QTL 效应共同构成产量优势，部分位点同时影响多个产量构成性状，显示性状间存在共享遗传基础。",
    keywords: ["Brassica napus", "heterosis", "QTL", "yield components", "rapeseed"]
  },
  {
    id: "schon-2010",
    title: "Genetic Composition of Yield Heterosis in an Elite Rice Hybrid",
    titleZh: "优良水稻杂交种产量杂种优势的遗传组成",
    authors: "Schön, C. C.; Dhillon, B. S.; Utz, H. F.; Melchinger, A. E.",
    journal: "Proceedings of the National Academy of Sciences",
    year: 2010,
    volume: "107",
    pages: "227–232",
    doi: "10.1073/pnas.0906570107",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析"],
    crops: ["水稻"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "研究结合大量分子标记和严谨的交配设计，估计水稻产量杂种优势中加性、显性和上位效应的相对贡献。",
    finding:
      "产量优势主要来自多位点效应及部分上位互作，观测到的优势并非由少数超大效应位点单独决定。",
    keywords: ["rice", "yield heterosis", "quantitative genetics", "epistasis"]
  },
  {
    id: "basunanda-2010",
    title:
      "Comparative Mapping of Quantitative Trait Loci Involved in Heterosis for Seedling and Yield Traits in Oilseed Rape (Brassica napus L.)",
    titleZh: "甘蓝型油菜苗期与产量性状杂种优势 QTL 的比较定位",
    authors: "Basunanda, P.; Radoev, M.; Ecke, W.; Friedt, W.; Becker, H. C.; Snowdon, R. J.",
    journal: "Theoretical and Applied Genetics",
    year: 2010,
    volume: "120",
    pages: "271–281",
    doi: "10.1007/s00122-009-1133-z",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析"],
    crops: ["油菜"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究比较油菜苗期活力与成熟产量性状的杂种优势 QTL，分析早期发育优势与最终产量之间的关系。",
    finding:
      "部分优势位点在苗期和产量阶段共享，说明早期生长优势可能是后续产量表现的组成部分，但两者并非完全重合。",
    keywords: ["oilseed rape", "seedling vigor", "yield heterosis", "QTL"]
  },
  {
    id: "larièpe-2012",
    title:
      "The Genetic Basis of Heterosis: Multiparental Quantitative Trait Loci Mapping Reveals Contrasted Levels of Apparent Overdominance among Traits of Agronomical Interest in Maize",
    titleZh: "杂种优势的遗传基础：多亲本 QTL 定位揭示玉米农艺性状中不同程度的表观超显性",
    authors: "Larièpe, A.; Mangin, B.; Jasson, S.; Combes, V.; Dumas, F.; Jamin, P.; Lariagon, C.; Jolivot, D.; Madur, D.; Fiévet, J.; Gallais, A.; Dubreuil, P.; Charcosset, A.; Moreau, L.",
    journal: "Genetics",
    year: 2012,
    volume: "190",
    pages: "795–811",
    doi: "10.1534/genetics.111.133447",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析"],
    crops: ["玉米"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究采用多亲本设计提高 QTL 定位分辨率，并检验不同农艺性状中表观超显性的比例和稳定性。",
    finding:
      "若干区段表现为表观超显性，但其中一部分可能由连锁位点的相斥显性效应造成，位点分辨率对机制判断至关重要。",
    keywords: ["multiparental QTL", "apparent overdominance", "maize", "agronomic traits"]
  },
  {
    id: "guo-2014-gwas",
    title: "Genome-Wide Association Study of Heterosis for Grain Yield and Its Components in Maize",
    titleZh: "玉米产量及产量构成杂种优势的全基因组关联研究",
    authors: "Guo, T.; Yang, N.; Tong, H.; Pan, Q.; Yang, X.; Tang, J.; Wang, J.; Li, J.; Yan, J.",
    journal: "PLOS ONE",
    year: 2014,
    volume: "9",
    pages: "e92736",
    doi: "10.1371/journal.pone.0092736",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "基因组与预测", "遗传解析"],
    crops: ["玉米"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究利用全基因组关联分析定位与玉米产量及其构成性状杂种优势相关的标记位点，连接连锁定位与自然群体变异。",
    finding:
      "优势相关位点数量多且效应分散，部分候选区域同时影响多个产量性状，支持复杂的多基因结构。",
    keywords: ["GWAS", "maize", "heterosis", "grain yield", "yield components"]
  },
  {
    id: "springer-stupar-2007",
    title: "Allelic Variation and Heterosis in Maize: How Do Two Halves Make More Than a Whole?",
    titleZh: "玉米等位变异与杂种优势：两个半份如何形成更大的整体？",
    authors: "Springer, N. M.; Stupar, R. M.",
    journal: "Genome Research",
    year: 2007,
    volume: "17",
    pages: "264–275",
    doi: "10.1101/gr.5347007",
    category: "转录机制",
    themes: ["转录与代谢", "遗传解析"],
    crops: ["玉米"],
    type: "综述",
    importance: "核心",
    summary:
      "文章从等位基因结构、表达差异和基因组变异角度解释玉米杂种优势，强调亲本单倍型的差异如何转化为杂交种表型。",
    finding:
      "等位基因表达差异、顺式与反式调控以及基因组结构变异，共同决定杂交后基因表达的非加性状态。",
    keywords: ["allelic variation", "gene expression", "maize", "heterosis", "regulatory divergence"]
  },
  {
    id: "swanson-wagner-2006",
    title:
      "All Possible Modes of Gene Action Are Observed in a Global Comparison of Gene Expression in a Maize F1 Hybrid and Its Inbred Parents",
    titleZh: "玉米 F1 与亲本表达比较中发现所有可能的基因作用模式",
    authors: "Swanson-Wagner, R. A.; Jia, Y.; DeCook, R.; Borsuk, L. A.; Nettleton, D.; Schnable, P. S.",
    journal: "Proceedings of the National Academy of Sciences",
    year: 2006,
    volume: "103",
    pages: "6805–6810",
    doi: "10.1073/pnas.0510430103",
    category: "转录机制",
    themes: ["转录与代谢", "遗传解析"],
    crops: ["玉米"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "研究以全基因组表达数据比较玉米杂交种和亲本，发现加性、显性、超显性及低亲/高亲表达等多种模式并存。",
    finding:
      "杂种优势不能被单一表达模式概括，不同基因可采取不同作用方式，转录层面的异质性非常明显。",
    keywords: ["gene expression", "additive", "dominance", "overdominance", "maize F1"]
  },
  {
    id: "paschold-2012",
    title:
      "Complementation Contributes to Transcriptome Complexity in Maize (Zea mays L.) Hybrids Relative to Their Inbred Parents",
    titleZh: "亲本互补增加玉米杂交种转录组复杂性",
    authors: "Paschold, A.; Jia, Y.; Marcon, C.; Lund, S.; Larson, N. B.; Yeh, C. T.; Ossowski, S.; Lanz, C.; Nettleton, D.; Schnable, P. S.; Hochholdinger, F.",
    journal: "Genome Research",
    year: 2012,
    volume: "22",
    pages: "2445–2454",
    doi: "10.1101/gr.138461.112",
    category: "转录机制",
    themes: ["转录与代谢", "遗传解析"],
    crops: ["玉米"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究在玉米根系中比较杂交种与亲本转录组，识别亲本特异表达基因在 F1 中的互补恢复。",
    finding:
      "杂交种能够表达亲本中相互缺失的转录本组合，转录组互补是形成更完整基因功能集合的重要机制。",
    keywords: ["transcriptome complementation", "maize root", "hybrid", "presence absence expression"]
  },
  {
    id: "lauss-2018",
    title: "Parental DNA Methylation States Are Associated with Heterosis in Epigenetic Hybrids",
    titleZh: "亲本 DNA 甲基化状态与表观杂交种杂种优势相关",
    authors: "Lauss, K.; Wardenaar, R.; Oka, R.; van Hulten, M. H. A.; Guryev, V.; Keurentjes, J. J. B.; Stam, M.; Johannes, F.",
    journal: "Plant Physiology",
    year: 2018,
    volume: "176",
    pages: "1627–1645",
    doi: "10.1104/pp.17.01054",
    category: "表观遗传",
    themes: ["表观遗传", "遗传解析"],
    crops: ["拟南芥"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究利用表观重组近交系构建“表观杂交种”，在不改变 DNA 序列的情况下检验亲本甲基化差异与杂种优势的关系。",
    finding:
      "亲本间特定甲基化状态差异与杂交后代表型优势相关，为表观遗传独立贡献杂种优势提供实验支持。",
    keywords: ["DNA methylation", "epigenetic hybrid", "heterosis", "epiRIL"]
  },
  {
    id: "greaves-2015",
    title: "Inheritance of Trans Chromosomal Methylation Patterns from Arabidopsis F1 Hybrids",
    titleZh: "拟南芥 F1 杂交种跨染色体甲基化模式的遗传",
    authors: "Greaves, I. K.; Groszmann, M.; Wang, A.; Peacock, W. J.; Dennis, E. S.",
    journal: "Proceedings of the National Academy of Sciences",
    year: 2015,
    volume: "112",
    pages: "4334–4339",
    doi: "10.1073/pnas.1413656112",
    category: "表观遗传",
    themes: ["表观遗传"],
    crops: ["拟南芥"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究追踪拟南芥杂交后跨染色体甲基化模式的变化及其在后续世代中的遗传，拓展了对杂交诱导表观变异的理解。",
    finding:
      "F1 中产生的部分甲基化变化可稳定传递，说明杂交不仅重组 DNA 序列，也能遗传新的表观状态。",
    keywords: ["trans chromosomal methylation", "F1 hybrid", "epigenetic inheritance", "Arabidopsis"]
  },
  {
    id: "springer-2009-pav",
    title:
      "Maize Inbreds Exhibit High Levels of Copy Number Variation (CNV) and Presence/Absence Variation (PAV) in Genome Content",
    titleZh: "玉米自交系基因组存在大量拷贝数变异与存在缺失变异",
    authors: "Springer, N. M.; Ying, K.; Fu, Y.; Ji, T.; Yeh, C. T.; Jia, Y.; Wu, W.; Richmond, T.; Kitzman, J.; Rosenbaum, H.; Iniguez, A. L.; Barbazuk, W. B.; Jeddeloh, J. A.; Nettleton, D.; Schnable, P. S.",
    journal: "PLOS Genetics",
    year: 2009,
    volume: "5",
    pages: "e1000734",
    doi: "10.1371/journal.pgen.1000734",
    category: "基因组变异",
    themes: ["基因组与预测", "遗传解析"],
    crops: ["玉米"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "研究系统比较多个玉米自交系的拷贝数和存在缺失变异，显示亲本基因组并非只有 SNP 层面的差异。",
    finding:
      "杂交亲本间存在大量基因结构变异，F1 可通过组合不同基因集合获得更广泛的遗传内容。",
    keywords: ["copy number variation", "presence absence variation", "maize", "genome structure"]
  },
  {
    id: "lai-2010",
    title: "Genome-Wide Patterns of Genetic Variation among Elite Maize Inbred Lines",
    titleZh: "优良玉米自交系全基因组遗传变异格局",
    authors: "Lai, J.; Li, R.; Xu, X.; Jin, W.; Xu, M.; Zhao, H.; Xiang, Z.; Song, W.; Ying, K.; Zhang, M.; et al.",
    journal: "Nature Genetics",
    year: 2010,
    volume: "42",
    pages: "1027–1030",
    doi: "10.1038/ng.684",
    category: "基因组变异",
    themes: ["基因组与预测", "育种应用"],
    crops: ["玉米"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究重测序多个优良玉米自交系，描绘与杂种优势群、育种历史和基因组分化相关的变异格局。",
    finding:
      "不同杂种优势群之间存在显著且结构化的遗传分化，为选择亲本和预测组合表现提供群体遗传基础。",
    keywords: ["maize inbred lines", "resequencing", "heterotic groups", "genetic variation"]
  },
  {
    id: "jiao-2012",
    title: "Genome-Wide Genetic Changes during Modern Breeding of Maize",
    titleZh: "现代玉米育种过程中的全基因组遗传变化",
    authors: "Jiao, Y.; Zhao, H.; Ren, L.; Song, W.; Qiu, B.; Guo, Y.; Liu, Z.; Zhang, M.; Hu, D.; Li, Y.; et al.",
    journal: "Nature Genetics",
    year: 2012,
    volume: "44",
    pages: "812–815",
    doi: "10.1038/ng.2312",
    category: "育种应用",
    themes: ["基因组与预测", "育种应用"],
    crops: ["玉米"],
    type: "机制研究",
    importance: "核心",
    summary:
      "文章比较不同育种时期玉米自交系的基因组变化，揭示现代育种如何改变等位基因频率和杂种优势群结构。",
    finding:
      "长期育种保留了与产量和适应相关的重要等位变异，同时使不同育种群体形成更清晰的分化边界。",
    keywords: ["modern breeding", "maize", "allele frequency", "genomic selection history"]
  },
  {
    id: "meuwissen-2001",
    title: "Prediction of Total Genetic Value Using Genome-Wide Dense Marker Maps",
    titleZh: "利用全基因组密集标记预测总遗传值",
    authors: "Meuwissen, T. H. E.; Hayes, B. J.; Goddard, M. E.",
    journal: "Genetics",
    year: 2001,
    volume: "157",
    pages: "1819–1829",
    doi: "10.1093/genetics/157.4.1819",
    category: "杂种预测",
    themes: ["杂种预测", "基因组与预测"],
    crops: ["综合"],
    type: "经典论文",
    importance: "奠基",
    summary:
      "该文提出并比较基因组选择的核心方法，包括最小二乘、贝叶斯收缩和机器学习思路，是现代基因组预测的奠基性论文。",
    finding:
      "高密度标记能够在训练群体中估计全基因组效应，并预测未观测个体的遗传值，显著缩短育种选择周期。",
    keywords: ["genomic selection", "dense markers", "Bayesian shrinkage", "prediction"]
  },
  {
    id: "bernardo-1994",
    title: "Prediction of Maize Single-Cross Performance Using RFLPs and Information from Related Hybrids",
    titleZh: "利用 RFLP 与相关杂交种信息预测玉米单交种表现",
    authors: "Bernardo, R.",
    journal: "Crop Science",
    year: 1994,
    volume: "34",
    pages: "20–25",
    doi: "10.2135/cropsci1994.0011183X003400010003x",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["玉米"],
    type: "育种应用",
    importance: "里程碑",
    summary:
      "研究较早利用分子标记和相关杂交种表现预测新的玉米单交种表现，奠定分子标记辅助杂种预测的基本思路。",
    finding:
      "亲本遗传距离和相关组合表型能提供有用预测信息，但单独使用距离指标不足以稳定预测产量。",
    keywords: ["single-cross prediction", "RFLP", "maize breeding", "related hybrids"]
  },
  {
    id: "bernardo-1996",
    title:
      "Testcross Additive and Dominance Effects in Best Linear Unbiased Prediction of Maize Single-Cross Performance",
    titleZh: "玉米单交种表现 BLUP 预测中的测交加性与显性效应",
    authors: "Bernardo, R.",
    journal: "Theoretical and Applied Genetics",
    year: 1996,
    volume: "93",
    pages: "1098–1102",
    doi: "10.1007/BF00230131",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["玉米"],
    type: "育种应用",
    importance: "核心",
    summary:
      "文章将加性、显性效应与最佳线性无偏预测结合，用于利用系谱和测交历史数据预测玉米单交种。",
    finding:
      "显性效应和亲本一般配合力是单交种预测的重要组成，混合模型能够整合历史测交信息提高排序能力。",
    keywords: ["BLUP", "testcross", "additive effect", "dominance effect", "maize"]
  },
  {
    id: "gianola-2006",
    title: "Genomic-Assisted Prediction of Genetic Value with Semiparametric Procedures",
    titleZh: "利用半参数方法开展基因组辅助遗传值预测",
    authors: "Gianola, D.; Fernando, R. L.; Stella, A.",
    journal: "Genetics",
    year: 2006,
    volume: "173",
    pages: "1761–1776",
    doi: "10.1534/genetics.105.049510",
    category: "杂种预测",
    themes: ["杂种预测", "基因组与预测"],
    crops: ["综合"],
    type: "机制研究",
    importance: "核心",
    summary:
      "文章引入核方法与半参数回归处理高维标记数据，强调复杂遗传效应对线性预测模型的挑战。",
    finding:
      "非线性半参数模型能够捕捉部分上位或复杂互作效应，但预测性能取决于样本量、标记结构和模型正则化。",
    keywords: ["semiparametric prediction", "kernel methods", "genomic value", "high-dimensional markers"]
  },
  {
    id: "habier-2007",
    title: "The Impact of Genetic Relationship Information on Genome-Assisted Breeding Values",
    titleZh: "遗传关系信息对基因组辅助育种值的影响",
    authors: "Habier, D.; Fernando, R. L.; Dekkers, J. C. M.",
    journal: "Genetics",
    year: 2007,
    volume: "177",
    pages: "2389–2397",
    doi: "10.1534/genetics.107.081190",
    category: "杂种预测",
    themes: ["杂种预测", "基因组与预测"],
    crops: ["综合"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究分析标记捕获系谱关系和连锁不平衡信息的方式，解释为何基因组预测精度会随训练群与预测群关系下降。",
    finding:
      "当预测个体与训练群体遗传关系较远时，标记仅能捕捉有限的连锁信息，预测精度通常明显降低。",
    keywords: ["genomic relationship", "prediction accuracy", "linkage disequilibrium", "training population"]
  },
  {
    id: "vanraden-2008",
    title: "Efficient Methods to Compute Genomic Predictions",
    titleZh: "基因组预测的高效计算方法",
    authors: "VanRaden, P. M.",
    journal: "Journal of Dairy Science",
    year: 2008,
    volume: "91",
    pages: "4414–4423",
    doi: "10.3168/jds.2007-0980",
    category: "杂种预测",
    themes: ["杂种预测", "基因组与预测"],
    crops: ["综合"],
    type: "经典论文",
    importance: "里程碑",
    summary:
      "文章提出广泛使用的 G 矩阵与基因组最佳线性无偏预测算法，大幅降低全基因组预测的计算门槛。",
    finding:
      "基于标记构建的关系矩阵可以高效替代传统系谱关系，支持大规模个体的基因组育种值同步估计。",
    keywords: ["GBLUP", "genomic relationship matrix", "prediction", "mixed model"]
  },
  {
    id: "windhausen-2012",
    title:
      "Effectiveness of Genomic Prediction of Maize Hybrid Performance in Different Breeding Populations and Environments",
    titleZh: "不同育种群体与环境下玉米杂交种表现基因组预测的有效性",
    authors: "Windhausen, V. S.; Atlin, G. N.; Hickey, J. M.; Crossa, J.; Jannink, J. L.; Sorrells, M. E.; Raman, B.; Cairns, J. E.; Tarekegne, A.; Semagn, K.; Beyene, Y.; Grudloyma, P.; Technow, F.; Riedelsheimer, C.; Melchinger, A. E.",
    journal: "G3: Genes, Genomes, Genetics",
    year: 2012,
    volume: "2",
    pages: "1427–1436",
    doi: "10.1534/g3.112.003699",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["玉米"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究在多个热带玉米育种群体和环境中评估基因组预测杂交种表现的能力，关注跨群体与环境迁移。",
    finding:
      "预测精度随群体关系、性状遗传力和环境条件变化，跨群体应用需要重新校准训练模型。",
    keywords: ["maize hybrid prediction", "genomic selection", "across environments", "breeding populations"]
  },
  {
    id: "deloscampos-2013",
    title: "Whole-Genome Regression and Prediction Methods Applied to Plant and Animal Breeding",
    titleZh: "应用于动植物育种的全基因组回归与预测方法",
    authors: "de los Campos, G.; Hickey, J. M.; Pong-Wong, R.; Daetwyler, H. D.; Calus, M. P. L.",
    journal: "Genetics",
    year: 2013,
    volume: "193",
    pages: "327–345",
    doi: "10.1534/genetics.112.143313",
    category: "杂种预测",
    themes: ["杂种预测", "基因组与预测", "育种应用"],
    crops: ["综合"],
    type: "综述",
    importance: "核心",
    summary:
      "综述系统比较全基因组回归、贝叶斯收缩、核方法与混合模型，梳理基因组预测在动植物育种中的共同统计基础。",
    finding:
      "不同预测方法在标记效应假设和计算效率上各有取舍，模型选择应匹配性状遗传结构和训练数据条件。",
    keywords: ["whole-genome regression", "Bayesian models", "genomic prediction", "plant breeding"]
  },
  {
    id: "techno-2014",
    title:
      "Genome Properties and Prospects of Genomic Prediction of Hybrid Performance in a Breeding Program of Maize",
    titleZh: "玉米育种程序中杂交种表现基因组预测的基因组性质与前景",
    authors: "Technow, F.; Schrag, T. A.; Schipprack, W.; Bauer, E.; Simianer, H.; Melchinger, A. E.",
    journal: "Genetics",
    year: 2014,
    volume: "197",
    pages: "1343–1355",
    doi: "10.1534/genetics.114.165860",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["玉米"],
    type: "育种应用",
    importance: "里程碑",
    summary:
      "研究在实际玉米育种程序中评估基因组预测杂交种表现的精度，并分析预测群体规模和训练策略的影响。",
    finding:
      "合理设计的训练群体可显著提高未测组合筛选效率，预测精度受亲本关系、性状结构与育种群体规模共同影响。",
    keywords: ["hybrid performance", "genomic prediction", "maize breeding program", "training set"]
  },
  {
    id: "schrag-2018",
    title:
      "Beyond Genomic Prediction: Combining Different Types of Omics Data Can Improve Prediction of Hybrid Performance in Maize",
    titleZh: "超越基因组预测：整合多类组学数据可提高玉米杂交种表现预测",
    authors: "Schrag, T. A.; Westhues, M.; Schipprack, W.; Seifert, F.; Thiemann, A.; Scholten, S.; Eisenreich, W.; Geist, B.; Engelmann, B.; Schnitzler, J. P.; Melchinger, A. E.",
    journal: "Genetics",
    year: 2018,
    volume: "208",
    pages: "1373–1385",
    doi: "10.1534/genetics.117.300374",
    category: "杂种预测",
    themes: ["杂种预测", "基因组与预测", "育种应用"],
    crops: ["玉米"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "研究比较基因组、转录组、代谢组和蛋白组数据对玉米杂种表现的预测能力，并评估多组学融合策略。",
    finding:
      "部分组学特征能够补充 DNA 标记信息，多组学组合在特定性状和群体中较单一基因组预测更有效。",
    keywords: ["multi-omics prediction", "maize hybrid", "transcriptome", "metabolome", "proteome"]
  },
  {
    id: "kadam-2019",
    title: "Genomic Prediction of Hybrid Performance in Grain Sorghum (Sorghum bicolor L.)",
    titleZh: "粒用高粱杂交种表现的基因组预测",
    authors: "Kadam, D. C.; Potts, S. M.; Bohn, M. O.; Lipka, A. E.; Lorenz, A. J.",
    journal: "Frontiers in Plant Science",
    year: 2019,
    volume: "10",
    pages: "1001",
    doi: "10.3389/fpls.2019.01001",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["高粱"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究在高粱育种群体中评估基因组预测杂交种性能的能力，比较加性、显性和组合模型。",
    finding:
      "显性和亲本组合信息能改善部分性状预测，但不同环境与训练群体设计会造成精度波动。",
    keywords: ["sorghum", "genomic prediction", "hybrid performance", "dominance"]
  },
  {
    id: "cui-2020",
    title: "Hybrid Breeding of Rice via Genomic Selection",
    titleZh: "利用基因组选择开展水稻杂交育种",
    authors: "Cui, Y.; Li, R.; Li, G.; Zhang, F.; Zhu, T.; Zhang, Q.; Ali, J.; Li, Z.; Xu, S.",
    journal: "Plant Biotechnology Journal",
    year: 2020,
    volume: "18",
    pages: "57–67",
    doi: "10.1111/pbi.13170",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["水稻"],
    type: "育种应用",
    importance: "里程碑",
    summary:
      "研究将基因组选择用于水稻杂交组合设计，评估其在训练、筛选和亲本改良中的实际应用价值。",
    finding:
      "基因组选择可帮助缩小待测组合范围，提高优良杂交种筛选效率，但预测精度依赖训练群体代表性。",
    keywords: ["hybrid rice", "genomic selection", "cross prediction", "breeding design"]
  },
  {
    id: "wang-2018-genomic-selection",
    title: "Genomic Selection Methods for Crop Improvement: Current Status and Prospects",
    titleZh: "作物改良中的基因组选择方法：现状与展望",
    authors: "Wang, X.; Xu, Y.; Hu, Z.; Xu, C.",
    journal: "The Crop Journal",
    year: 2018,
    volume: "6",
    pages: "330–340",
    doi: "10.1016/j.cj.2018.03.005",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["综合"],
    type: "综述",
    importance: "核心",
    summary:
      "综述梳理作物基因组选择的统计方法、训练策略与实施流程，并讨论复杂性状、环境互作和大数据带来的挑战。",
    finding:
      "提高预测效果不仅依赖模型创新，还需要优化群体设计、表型质量、标记密度与跨环境验证。",
    keywords: ["genomic selection", "crop improvement", "prediction model", "training design"]
  },
  {
    id: "duvick-2005",
    title: "The Contribution of Breeding to Yield Advances in Maize (Zea mays L.)",
    titleZh: "育种对玉米产量提升的贡献",
    authors: "Duvick, D. N.",
    journal: "Advances in Agronomy",
    year: 2005,
    volume: "86",
    pages: "83–145",
    doi: "10.1016/S0065-2113(05)86002-X",
    category: "育种应用",
    themes: ["育种应用", "经典假说"],
    crops: ["玉米"],
    type: "综述",
    importance: "里程碑",
    summary:
      "Duvick 回顾美国玉米产量长期增长中遗传改良与管理措施的贡献，强调杂交育种和品种适应性的核心作用。",
    finding:
      "现代杂交种在抗逆性、密度适应和稳产性上的改良与产量提升同等重要，杂种优势利用是长期育种体系的结果。",
    keywords: ["maize yield gain", "hybrid breeding", "stress tolerance", "genetic gain"]
  },
  {
    id: "troyer-2006",
    title: "Adaptedness and Heterosis in Corn and Mule Hybrids",
    titleZh: "玉米与骡子杂交种中的适应性与杂种优势",
    authors: "Troyer, A. F.",
    journal: "Crop Science",
    year: 2006,
    volume: "46",
    pages: "528–543",
    doi: "10.2135/cropsci2005.0065",
    category: "育种应用",
    themes: ["经典假说", "育种应用"],
    crops: ["玉米"],
    type: "综述",
    importance: "核心",
    summary:
      "文章比较玉米杂交种与骡子在适应性、活力和生殖隔离方面的表现，强调杂种优势并不等同于繁殖优势。",
    finding:
      "强营养体活力可与生殖适合度下降并存，杂种优势在农业性状与进化适合度之间可能呈现不同方向。",
    keywords: ["adaptedness", "mule hybrid", "maize", "fitness", "heterosis"]
  },
  {
    id: "yuan-1966",
    title: "水稻的雄性不孕性",
    titleZh: "水稻雄性不育的发现及其杂交育种意义",
    authors: "袁隆平",
    journal: "科学通报",
    year: 1966,
    volume: "17",
    pages: "185–188",
    doi: "",
    category: "育种应用",
    themes: ["育种应用", "经典假说"],
    crops: ["水稻"],
    type: "经典论文",
    importance: "奠基",
    summary:
      "袁隆平提出利用水稻雄性不育材料开展杂交育种的设想，为中国杂交水稻体系的建立奠定关键基础。",
    finding:
      "可利用雄性不育系、保持系与恢复系的三系配套，实现大规模杂交稻制种并系统利用杂种优势。",
    keywords: ["雄性不育", "杂交水稻", "三系法", "heterosis utilization"]
  },
  {
    id: "charlesworth-1987",
    title: "Inbreeding Depression and Its Evolutionary Consequences",
    titleZh: "近交衰退及其进化后果",
    authors: "Charlesworth, D.; Charlesworth, B.",
    journal: "Annual Review of Ecology and Systematics",
    year: 1987,
    volume: "18",
    pages: "237–268",
    doi: "10.1146/annurev.es.18.110187.001321",
    category: "经典奠基",
    themes: ["经典假说", "遗传解析"],
    crops: ["综合"],
    type: "综述",
    importance: "奠基",
    summary:
      "文章系统总结近交衰退的遗传机制与进化后果，为理解杂交恢复活力、遗传负荷和群体适合度提供理论背景。",
    finding:
      "有害隐性等位基因纯合、超显性和环境依赖选择均可导致近交衰退，其相对贡献随群体历史与性状类型变化。",
    keywords: ["inbreeding depression", "evolution", "mutation load", "overdominance"]
  },
  {
    id: "giraud-2022",
    title: "Hybrid Vigor: The Best of Both Parents, or a Genomic Clash?",
    titleZh: "杂种活力：亲本优势的叠加，还是基因组的碰撞？",
    authors: "Giraud, H.; Courtois, B.; Vigouroux, Y.; et al.",
    journal: "Current Opinion in Plant Biology",
    year: 2022,
    volume: "66",
    pages: "102191",
    doi: "10.1016/j.pbi.2022.102191",
    category: "分子机制",
    themes: ["经典假说", "遗传解析", "基因组与预测"],
    crops: ["综合"],
    type: "综述",
    importance: "新进展",
    summary:
      "文章从互补、冲突和调控重组等角度重新审视杂种优势，讨论为何亲本基因组组合既可能带来增益，也可能产生不相容。",
    finding:
      "杂种表型是多位点互作、调控网络和基因组冲突的综合结果，统一机制需要同时解释优势与杂交劣势。",
    keywords: ["hybrid vigor", "genomic conflict", "complementation", "regulatory incompatibility"]
  },
  {
    id: "zhao-2013-wheat",
    title: "Genomic Prediction of Hybrid Wheat Performance",
    titleZh: "杂交小麦表现的基因组预测",
    authors: "Zhao, Y.; Zeng, J.; Fernando, R.; Reif, J. C.",
    journal: "Crop Science",
    year: 2013,
    volume: "53",
    pages: "802–810",
    doi: "10.2135/cropsci2012.08.0463",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["小麦"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "里程碑",
    summary:
      "该研究把基因组预测引入杂交小麦育种，比较不同统计模型对亲本组合表现与一般配合力的预测能力。",
    finding:
      "全基因组标记能够有效预测小麦杂交种表现，在训练群体代表性的前提下可显著缩小田间测试规模。",
    keywords: ["hybrid wheat", "genomic prediction", "combining ability", "training population"]
  },
  {
    id: "reif-2013-sunflower",
    title: "Genomic Prediction of Sunflower Hybrid Performance",
    titleZh: "向日葵杂交种表现的基因组预测",
    authors: "Reif, J. C.; Zhao, Y.; Würschum, T.; Gowda, M.; Hahn, V.",
    journal: "Plant Breeding",
    year: 2013,
    volume: "132",
    pages: "107–114",
    doi: "10.1111/pbr.12007",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["向日葵"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究评估 SNP 标记预测向日葵杂交种产量和品质性状的能力，并比较亲本效应与组合效应模型。",
    finding:
      "基因组预测对联合作物表现具有应用潜力，跨环境稳定性与训练群体规模会直接影响预测精度。",
    keywords: ["sunflower", "hybrid performance", "genomic prediction", "SNP"]
  },
  {
    id: "gowda-2013-triticale",
    title: "Best Linear Unbiased Prediction of Triticale Hybrid Performance",
    titleZh: "小黑麦杂交种表现的最佳线性无偏预测",
    authors: "Gowda, M.; Zhao, Y.; Maurer, H. P.; Weissmann, E. A.; Würschum, T.; Reif, J. C.",
    journal: "Euphytica",
    year: 2013,
    volume: "191",
    pages: "223–230",
    doi: "10.1007/s10681-012-0784-z",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["小黑麦"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究利用 BLUP 整合系谱和亲缘关系信息预测小黑麦杂交种表现，为自交作物的杂交育种设计提供统计工具。",
    finding:
      "结合系谱关系的混合模型可提高未测组合的排序能力，比仅依赖亲本表型更有效。",
    keywords: ["triticale", "BLUP", "hybrid performance", "pedigree"]
  },
  {
    id: "philipp-2016-barley",
    title: "Genomic Prediction of Barley Hybrid Performance",
    titleZh: "大麦杂交种表现的基因组预测",
    authors: "Philipp, N.; Liu, G.; Zhao, Y.; He, S.; Spiller, M.; Stiewe, G.; Pillen, K.; Reif, J. C.; Li, Z.",
    journal: "The Plant Genome",
    year: 2016,
    volume: "9",
    pages: "",
    doi: "10.3835/plantgenome2016.02.0016",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["大麦"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究评估基因组预测在大麦杂交育种中的表现，关注加性、显性效应及不同训练群体设计。",
    finding:
      "标记预测可辅助筛选大麦杂交组合，但杂种优势和性状复杂性会限制跨群体模型的迁移能力。",
    keywords: ["barley", "hybrid performance", "genomic prediction", "training design"]
  },
  {
    id: "zhao-2015-hybrid-selection",
    title: "Genomic Selection in Hybrid Breeding",
    titleZh: "杂交育种中的基因组选择",
    authors: "Zhao, Y.; Mette, M. F.; Reif, J. C.",
    journal: "Plant Breeding",
    year: 2015,
    volume: "134",
    pages: "1–10",
    doi: "10.1111/pbr.12231",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["综合"],
    teams: ["IPK / Reif 团队"],
    type: "综述",
    importance: "里程碑",
    summary:
      "文章总结基因组选择用于杂交育种的模型、训练群体设计和亲本组合预测，是 Reif/IPK 团队的代表性综述。",
    finding:
      "基因组选择能够缩短杂交育种周期，但需要针对亲本关系、群体结构和目标性状设计训练与验证方案。",
    keywords: ["genomic selection", "hybrid breeding", "testcross", "prediction accuracy"]
  },
  {
    id: "lell-2021-wheat-trials",
    title: "Optimizing the Setup of Multienvironmental Hybrid Wheat Yield Trials for Boosting the Selection Capability",
    titleZh: "优化多环境杂交小麦产量试验以提高选择能力",
    authors: "Lell, M.; Reif, J. C.; Zhao, Y.",
    journal: "The Plant Genome",
    year: 2021,
    volume: "14",
    pages: "e20150",
    doi: "10.1002/tpg2.20150",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["小麦"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究比较不同多环境试验布局与资源分配对杂交小麦选择效果的影响，连接统计预测与育种资源决策。",
    finding:
      "增加环境数量和优化组合分配可提高遗传效应估计与选择准确性，但需要平衡单点重复和总体测试规模。",
    keywords: ["multienvironment trials", "hybrid wheat", "selection capability", "resource allocation"]
  },
  {
    id: "schulthess-2018-multitrait",
    title: "Advantages and Limitations of Multiple-Trait Genomic Prediction for Fusarium Head Blight Severity in Hybrid Wheat",
    titleZh: "杂交小麦赤霉病严重度多性状基因组预测的优势与局限",
    authors: "Schulthess, A. W.; Zhao, Y.; Longin, C. F. H.; Reif, J. C.",
    journal: "Theoretical and Applied Genetics",
    year: 2018,
    volume: "131",
    pages: "685–701",
    doi: "10.1007/s00122-017-3029-7",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["小麦"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究检验多性状模型能否利用相关农艺性状提高杂交小麦赤霉病预测，并分析不同性状组合的效果。",
    finding:
      "相关性状可为目标性状提供额外信息，但模型收益依赖遗传相关强度、表型质量与训练群体规模。",
    keywords: ["multitrait prediction", "Fusarium head blight", "hybrid wheat", "genomic selection"]
  },
  {
    id: "jiang-2017-wheat-epistasis",
    title: "A Quantitative Genetic Framework Highlights the Role of Epistatic Effects for Grain-Yield Heterosis in Bread Wheat",
    titleZh: "数量遗传框架揭示上位性效应对面包小麦产量杂种优势的作用",
    authors: "Jiang, Y.; Schmidt, R. H.; Zhao, Y.; Reif, J. C.",
    journal: "Nature Genetics",
    year: 2017,
    volume: "49",
    pages: "1741–1746",
    doi: "10.1038/ng.3974",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析", "杂种预测"],
    crops: ["小麦"],
    teams: ["IPK / Reif 团队"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "该研究构建数量遗传框架，在面包小麦中同步估计加性、显性和上位效应对产量杂种优势的贡献。",
    finding:
      "上位性效应在小麦产量杂种优势中占据重要地位，只使用加性和显性模型会低估复杂互作的作用。",
    keywords: ["wheat heterosis", "epistasis", "quantitative genetics", "grain yield"]
  },
  {
    id: "rembe-2019-rrgs",
    title: "Reciprocal Recurrent Genomic Selection: An Attractive Tool to Leverage Hybrid Wheat Breeding",
    titleZh: "相互轮回基因组选择：提升杂交小麦育种的有力工具",
    authors: "Rembe, M.; Zhao, Y.; Jiang, Y.; Reif, J. C.",
    journal: "Theoretical and Applied Genetics",
    year: 2019,
    volume: "132",
    pages: "687–698",
    doi: "10.1007/s00122-018-3244-x",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["小麦"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "里程碑",
    summary:
      "研究提出并评估相互轮回基因组选择策略，通过同步改良两个互补亲本群体提高杂交小麦长期育种增益。",
    finding:
      "将相互轮回选择与基因组预测结合，可提高一般配合力和组合表现，并保持两个亲本群之间的互补性。",
    keywords: ["reciprocal recurrent selection", "genomic selection", "hybrid wheat", "long-term gain"]
  },
  {
    id: "longin-2014-hybrid-line",
    title: "Long-Term Perspective of Hybrid Versus Line Breeding in Wheat Based on Quantitative Genetic Theory",
    titleZh: "基于数量遗传理论的杂交小麦与纯系育种长期比较",
    authors: "Longin, C. F. H.; Reif, J. C.; Würschum, T.",
    journal: "Theoretical and Applied Genetics",
    year: 2014,
    volume: "127",
    pages: "1635–1641",
    doi: "10.1007/s00122-014-2325-8",
    category: "育种应用",
    themes: ["育种应用", "遗传解析"],
    crops: ["小麦"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "核心",
    summary:
      "文章用数量遗传模型比较杂交育种与纯系育种的长期选择增益，分析杂种优势与制种成本的平衡。",
    finding:
      "杂交育种能否优于纯系育种取决于杂种优势、亲本改良速度和种子生产成本，并不存在普适结论。",
    keywords: ["hybrid breeding", "line breeding", "long-term selection", "wheat"]
  },
  {
    id: "li-2020-northwest-maize",
    title: "Genome-Wide Prediction in a Hybrid Maize Population Adapted to Northwest China",
    titleZh: "适应中国西北地区的杂交玉米群体全基因组预测",
    authors: "Li, G.; Dong, Y.; Zhao, Y.; Tian, X.; Würschum, T.; Xue, J.; Chen, S.; Reif, J. C.; Xu, S.; Liu, W.",
    journal: "The Crop Journal",
    year: 2020,
    volume: "8",
    pages: "830–842",
    doi: "10.1016/j.cj.2020.04.006",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["玉米"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究针对中国西北适应型玉米群体开展全基因组预测，评估不同模型和亲本组合预测策略。",
    finding:
      "合理纳入亲本关系和群体结构信息可改善复杂产量性状预测，区域育种群体的训练设计尤为关键。",
    keywords: ["maize", "Northwest China", "genome-wide prediction", "hybrid population"]
  },
  {
    id: "beukert-2020-rust",
    title: "Comparing the Potential of Marker-Assisted Selection and Genomic Prediction for Improving Rust Resistance in Hybrid Wheat",
    titleZh: "标记辅助选择与基因组预测改良杂交小麦锈病抗性的潜力比较",
    authors: "Beukert, U.; Thorwarth, P.; Zhao, Y.; Longin, C. F. H.; Serfling, A.; Ordon, F.; Reif, J. C.",
    journal: "Frontiers in Plant Science",
    year: 2020,
    volume: "11",
    pages: "594113",
    doi: "10.3389/fpls.2020.594113",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["小麦"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究比较已知抗病标记与全基因组预测在杂交小麦锈病抗性改良中的效果，关注多基因抗性。",
    finding:
      "主效标记适合快速筛选，全基因组模型更适合由多基因控制的抗性；两者组合可提高选择效率。",
    keywords: ["rust resistance", "marker-assisted selection", "genomic prediction", "hybrid wheat"]
  },
  {
    id: "whitford-2013-hybrid-wheat",
    title: "Hybrid Breeding in Wheat: Technologies to Improve Hybrid Wheat Seed Production",
    titleZh: "小麦杂交育种：提高杂交种子生产的技术路线",
    authors: "Whitford, R.; Fleury, D.; Reif, J. C.; Garcia, M.; Okada, T.; Korzun, V.; Langridge, P.",
    journal: "Journal of Experimental Botany",
    year: 2013,
    volume: "64",
    pages: "5411–5428",
    doi: "10.1093/jxb/ert333",
    category: "育种应用",
    themes: ["育种应用", "经典假说"],
    crops: ["小麦"],
    teams: ["IPK / Reif 团队"],
    type: "综述",
    importance: "里程碑",
    summary:
      "综述系统讨论杂交小麦制种体系、雄性不育、恢复系和花期同步等技术瓶颈，连接杂种优势理论与商业化应用。",
    finding:
      "杂交小麦能否规模化取决于制种效率、亲本繁殖和杂种优势共同构成的经济性，而不只是产量优势大小。",
    keywords: ["hybrid wheat", "seed production", "male sterility", "restorer"]
  },
  {
    id: "li-2026-wheat-heterosis",
    title: "Genetic Dissection of Wheat Heterosis Identifies Candidate Genes in Biparental and Diverse Hybrid Populations",
    titleZh: "小麦杂种优势遗传解析在双亲和多亲本杂交群体中鉴定候选基因",
    authors: "Li, G.; Chu, J.; Haupt, M.; Jiang, Y.; Reif, J. C.",
    journal: "Plant Biotechnology Journal",
    year: 2026,
    volume: "",
    pages: "",
    doi: "10.1111/pbi.70748",
    category: "位点鉴定",
    themes: ["杂种优势位点鉴定", "遗传解析", "基因组与预测"],
    crops: ["小麦"],
    teams: ["IPK / Reif 团队"],
    type: "机制研究",
    importance: "新进展",
    summary:
      "研究整合双亲与多亲本杂交群体的定位信息，从不同遗传背景中识别与小麦杂种优势相关的候选基因。",
    finding:
      "跨群体重复的候选位点比单群体特异信号更具应用价值，位点效应受亲本背景与性状结构影响。",
    keywords: ["wheat heterosis", "candidate genes", "multiparental population", "genetic dissection"]
  },
  {
    id: "schmidt-2024-flowering",
    title: "Hybrid Grain Production in Wheat Benefits from Synchronized Flowering and High Female Flower Receptivity",
    titleZh: "花期同步与高雌花可授性促进小麦杂交制种",
    authors: "Schmidt, C.; Hinterberger, V.; Philipp, N.; Reif, J. C.; Schnurbusch, T.",
    journal: "Journal of Experimental Botany",
    year: 2024,
    volume: "76",
    pages: "445–460",
    doi: "10.1093/jxb/erae430",
    category: "育种应用",
    themes: ["育种应用", "转录与代谢"],
    crops: ["小麦"],
    teams: ["IPK / Reif 团队"],
    type: "机制研究",
    importance: "新进展",
    summary:
      "研究分析小麦杂交制种中的花期同步、雌花可授性和结实效率，揭示影响制种产量的发育性状。",
    finding:
      "花期匹配和雌蕊可授期延长能够提高异交结实率，是杂交小麦商业化的重要农艺基础。",
    keywords: ["flowering synchrony", "female receptivity", "hybrid seed", "wheat"]
  },
  {
    id: "reif-2012-genetic-basis",
    title: "Genetic Basis of Heterosis and Prediction of Hybrid Performance",
    titleZh: "杂种优势的遗传基础与杂种表现预测",
    authors: "Reif, J. C.; Hahn, V.; Melchinger, A. E.",
    journal: "Helia",
    year: 2012,
    volume: "35",
    pages: "1–7",
    doi: "10.2298/hel1257001r",
    category: "杂种预测",
    themes: ["杂种预测", "经典假说", "育种应用"],
    crops: ["综合"],
    teams: ["IPK / Reif 团队"],
    type: "综述",
    importance: "核心",
    summary:
      "文章连接杂种优势遗传机制与杂种表现预测，讨论配合力、遗传距离和分子标记在组合筛选中的作用。",
    finding:
      "预测模型需要反映非加性遗传效应与亲本关系，单纯遗传距离通常不足以稳定预测复杂杂种表现。",
    keywords: ["heterosis", "hybrid prediction", "combining ability", "genetic distance"]
  },
  {
    id: "reif-2003-ssr-maize",
    title: "Genetic Distance Based on Simple Sequence Repeats and Heterosis in Tropical Maize Populations",
    titleZh: "热带玉米群体 SSR 遗传距离与杂种优势",
    authors: "Reif, J. C.; Melchinger, A. E.; Xia, X. C.; Warburton, M. L.; Hoisington, D. A.; Vasal, S. K.; Srinivasan, G.; Bohn, M.; Frisch, M.",
    journal: "Crop Science",
    year: 2003,
    volume: "43",
    pages: "1275–1282",
    doi: "10.2135/cropsci2003.1275",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["玉米"],
    teams: ["IPK / Reif 团队"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究评估 SSR 遗传距离预测热带玉米群体杂种优势的能力，检验分子距离与组合表现之间的关系。",
    finding:
      "遗传距离与杂种优势存在总体相关，但不同群体和性状间关系不稳定，不能替代实际测配。",
    keywords: ["SSR", "genetic distance", "heterosis", "tropical maize"]
  },
  {
    id: "gowda-2010-durum",
    title: "Hybrid Breeding in Durum Wheat: Heterosis and Combining Ability",
    titleZh: "硬粒小麦杂交育种：杂种优势与配合力",
    authors: "Gowda, M.; Kling, C.; Würschum, T.; Liu, W.; Maurer, H. P.; Hahn, V.; Reif, J. C.",
    journal: "Crop Science",
    year: 2010,
    volume: "50",
    pages: "2224–2230",
    doi: "10.2135/cropsci2009.10.0637",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["小麦"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究估计硬粒小麦杂交组合的杂种优势与一般、特殊配合力，为杂交硬粒小麦育种提供参数基础。",
    finding:
      "产量和株型性状存在可利用杂种优势，但亲本一般配合力对组合表现具有重要影响。",
    keywords: ["durum wheat", "combining ability", "heterosis", "hybrid breeding"]
  },
  {
    id: "wurschum-2023-distance",
    title: "Maximization Through Optimization? On the Relationship Between Hybrid Performance and Parental Genetic Distance",
    titleZh: "通过优化实现最大化？杂种表现与亲本遗传距离的关系",
    authors: "Würschum, T.; Zhu, X.; Zhao, Y.; Jiang, Y.; Reif, J. C.; Maurer, H. P.",
    journal: "Theoretical and Applied Genetics",
    year: 2023,
    volume: "136",
    pages: "",
    doi: "10.1007/s00122-023-04436-5",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["综合"],
    teams: ["IPK / Reif 团队"],
    type: "机制研究",
    importance: "新进展",
    summary:
      "研究重新检验亲本遗传距离与杂种表现之间的关系，讨论单纯追求远缘组合是否总能最大化杂种优势。",
    finding:
      "遗传距离与杂种表现通常不是单调关系，过远亲本可能引入不亲和与配合力下降，组合预测仍需模型化。",
    keywords: ["parental genetic distance", "hybrid performance", "heterotic pattern", "optimization"]
  },
  {
    id: "longin-2012-autogamous",
    title: "Hybrid Breeding in Autogamous Cereals",
    titleZh: "自花授粉谷物的杂交育种",
    authors: "Longin, C. F. H.; Mühleisen, J.; Maurer, H. P.; Zhang, H.; Gowda, M.; Reif, J. C.",
    journal: "Theoretical and Applied Genetics",
    year: 2012,
    volume: "125",
    pages: "1087–1096",
    doi: "10.1007/s00122-012-1967-7",
    category: "育种应用",
    themes: ["育种应用", "杂种预测"],
    crops: ["小麦", "大麦"],
    teams: ["IPK / Reif 团队"],
    type: "综述",
    importance: "里程碑",
    summary:
      "综述梳理自花授粉谷物杂交育种的技术路线、制种体系和杂种优势水平，重点讨论小麦与大麦。",
    finding:
      "自交作物杂交育种的可行性取决于制种系统、杂种优势和亲本群体改良速度的共同作用。",
    keywords: ["autogamous cereals", "hybrid breeding", "wheat", "barley", "seed production"]
  },
  {
    id: "muhleisen-2013-barley",
    title: "Hybrid Breeding in Barley",
    titleZh: "大麦杂交育种",
    authors: "Mühleisen, J.; Maurer, H. P.; Stiewe, G.; Bury, P.; Reif, J. C.",
    journal: "Crop Science",
    year: 2013,
    volume: "53",
    pages: "819–824",
    doi: "10.2135/cropsci2012.07.0411",
    category: "育种应用",
    themes: ["育种应用", "杂种预测"],
    crops: ["大麦"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究评估大麦杂交种的农艺表现、杂种优势与制种潜力，分析杂交大麦的育种价值。",
    finding:
      "部分大麦杂交组合在产量和抗逆性上表现优势，但商业化仍受制种效率和经济性制约。",
    keywords: ["barley", "hybrid breeding", "heterosis", "seed production"]
  },
  {
    id: "hubner-2012-rye",
    title: "Hybrid Rye Performance Under Natural Drought Stress in Europe",
    titleZh: "欧洲自然干旱条件下杂交黑麦表现",
    authors: "Hübner, M.; Wilde, P.; Schmiedchen, B.; Dopierala, P.; Gowda, M.; Reif, J. C.; Miedaner, T.",
    journal: "Theoretical and Applied Genetics",
    year: 2012,
    volume: "126",
    pages: "475–482",
    doi: "10.1007/s00122-012-1994-4",
    category: "育种应用",
    themes: ["育种应用", "杂种预测"],
    crops: ["黑麦"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究在欧洲多点自然干旱环境中评估杂交黑麦产量表现，分析杂种优势在胁迫环境下的稳定性。",
    finding:
      "杂交黑麦在干旱条件下仍可获得产量优势，但不同环境间的优势幅度受水分胁迫强度影响。",
    keywords: ["hybrid rye", "drought stress", "heterosis", "multi-environment"]
  },
  {
    id: "jiang-2015-modeling-epistasis",
    title: "Modeling Epistasis in Genomic Selection",
    titleZh: "基因组选择中的上位性建模",
    authors: "Jiang, Y.; Reif, J. C.",
    journal: "Genetics",
    year: 2015,
    volume: "201",
    pages: "759–768",
    doi: "10.1534/genetics.115.177907",
    category: "杂种预测",
    themes: ["杂种预测", "遗传解析"],
    crops: ["综合"],
    teams: ["IPK / Reif 团队"],
    type: "机制研究",
    importance: "里程碑",
    summary:
      "文章提出在基因组预测中显式纳入上位性效应的统计建模方法，并评估其对复杂性状预测的影响。",
    finding:
      "上位模型在互作效应真实存在时可提高预测能力，但参数数量快速增加，对训练群体规模和计算资源要求更高。",
    keywords: ["epistasis", "genomic selection", "prediction model", "interaction"]
  },
  {
    id: "jiang-2020-epistatic-grm",
    title: "Efficient Algorithms for Calculating Epistatic Genomic Relationship Matrices",
    titleZh: "高效计算上位性基因组关系矩阵的算法",
    authors: "Jiang, Y.; Reif, J. C.",
    journal: "Genetics",
    year: 2020,
    volume: "216",
    pages: "651–669",
    doi: "10.1534/genetics.120.303459",
    category: "杂种预测",
    themes: ["杂种预测", "基因组与预测"],
    crops: ["综合"],
    teams: ["IPK / Reif 团队"],
    type: "机制研究",
    importance: "核心",
    summary:
      "研究开发高效算法计算多种上位性基因组关系矩阵，降低大规模育种数据中互作预测的计算成本。",
    finding:
      "优化算法能够在不显式构建超大矩阵的情况下完成上位性预测，为实际育种群体应用提供可扩展方案。",
    keywords: ["epistatic relationship matrix", "algorithm", "genomic prediction", "large-scale data"]
  },
  {
    id: "gundala-2026-training",
    title: "The Value of Training Population Optimization Strategies for Genomic Prediction in the Era of Large Integrated Data",
    titleZh: "大规模整合数据时代训练群体优化对基因组预测的价值",
    authors: "Gundala, P.; Reif, J. C.; Zhao, Y.",
    journal: "The Crop Journal",
    year: 2026,
    volume: "",
    pages: "",
    doi: "10.1016/j.cj.2026.08.012",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用", "基因组与预测"],
    crops: ["综合"],
    teams: ["IPK / Reif 团队"],
    type: "综述",
    importance: "新进展",
    summary:
      "文章总结大规模整合数据背景下的训练群体优化策略，讨论如何选择最有信息量的个体和群体进行建模。",
    finding:
      "训练群体优化可比单纯扩大数据规模更有效地提高预测精度，尤其适用于跨群体和跨环境预测。",
    keywords: ["training population optimization", "genomic prediction", "large data", "sampling"]
  },
  {
    id: "saxena-2021-pigeonpea",
    title: "Characterization of Heterosis and Genomic Prediction-Based Establishment of Heterotic Patterns for Developing Better Hybrids in Pigeonpea",
    titleZh: "木豆杂种优势表征与基于基因组预测的杂种优势群构建",
    authors: "Saxena, R. K.; Jiang, Y.; Khan, A. W.; Zhao, Y.; Kumar Singh, V.; Bohra, A.; Sonappa, M.; Rathore, A.; Kumar, C. V.; Saxena, K. B.; Reif, J. C.; Varshney, R. K.",
    journal: "The Plant Genome",
    year: 2021,
    volume: "14",
    pages: "e20125",
    doi: "10.1002/tpg2.20125",
    category: "杂种预测",
    themes: ["杂种预测", "育种应用"],
    crops: ["木豆"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究结合杂种优势表型与基因组预测构建木豆杂种优势群，为豆科作物的杂交育种提供路线。",
    finding:
      "基于基因组信息划分的优势群能够提高亲本组合预测效率，并帮助识别具有强优势潜力的跨群组合。",
    keywords: ["pigeonpea", "heterotic pattern", "genomic prediction", "hybrid breeding"]
  },
  {
    id: "paril-2023-heterosis-improvement",
    title: "Heterosis in Crop Improvement",
    titleZh: "作物改良中的杂种优势",
    authors: "Paril, J.; Reif, J. C.; Fournier-Level, A.; Pourkheirandish, M.",
    journal: "The Plant Journal",
    year: 2023,
    volume: "117",
    pages: "23–32",
    doi: "10.1111/tpj.16488",
    category: "分子机制",
    themes: ["经典假说", "杂种预测", "育种应用"],
    crops: ["综合"],
    teams: ["IPK / Reif 团队"],
    type: "综述",
    importance: "新进展",
    summary:
      "综述从遗传机制、育种设计和预测方法三个层面讨论作物杂种优势利用的最新进展。",
    finding:
      "未来杂种优势利用需要更好整合因果变异、组合预测、制种技术和环境适应。",
    keywords: ["crop improvement", "heterosis", "hybrid breeding", "prediction"]
  },
  {
    id: "gogna-2023-selective-constraint",
    title: "Filtering for SNPs with High Selective Constraint Augments Mid-Parent Heterosis Predictions in Wheat",
    titleZh: "筛选高选择约束 SNP 可增强小麦中亲杂种优势预测",
    authors: "Gogna, A.; Zhang, Y.; Jiang, Y.; Schulthess, A. W.; Zhao, Y.; Reif, J. C.",
    journal: "The Crop Journal",
    year: 2023,
    volume: "11",
    pages: "166–176",
    doi: "10.1016/j.cj.2022.06.009",
    category: "杂种预测",
    themes: ["杂种预测", "基因组与预测"],
    crops: ["小麦"],
    teams: ["IPK / Reif 团队"],
    type: "机制研究",
    importance: "新进展",
    summary:
      "研究检验按进化选择约束筛选 SNP 是否能够改善小麦中亲杂种优势预测，连接功能约束与预测模型。",
    finding:
      "保留受强选择约束的标记可以减少噪声并提高部分性状预测精度，但标记筛选策略需结合目标群体验证。",
    keywords: ["selective constraint", "mid-parent heterosis", "SNP filtering", "wheat"]
  },
  {
    id: "schwarzwalder-2022-quality",
    title: "Hybrid Wheat: Quantitative Genetic Parameters and Heterosis for Quality and Rheological Traits as Well as Baking Volume",
    titleZh: "杂交小麦品质、流变学性状及烘焙体积的数量遗传参数与杂种优势",
    authors: "Schwarzwälder, L.; Thorwarth, P.; Zhao, Y.; Reif, J. C.; Longin, C. F. H.",
    journal: "Theoretical and Applied Genetics",
    year: 2022,
    volume: "135",
    pages: "1131–1141",
    doi: "10.1007/s00122-022-04039-6",
    category: "育种应用",
    themes: ["育种应用", "杂种预测"],
    crops: ["小麦"],
    teams: ["IPK / Reif 团队"],
    type: "育种应用",
    importance: "核心",
    summary:
      "研究系统估计杂交小麦品质、流变学与烘焙体积相关性状的遗传参数和杂种优势。",
    finding:
      "部分品质性状存在可利用杂种优势，但产量与品质的组合改良需要同时考虑性状间相关和亲本配合力。",
    keywords: ["hybrid wheat", "quality traits", "rheology", "baking volume", "heterosis"]
  }
];
